package location.app.vehicule_location_app.models;

public enum NotificationType {

        // CLient Notifications
        CLIENT_NEW_RESERVATION,
        CLIENT_RESERVATION_MODIFICATION_REQUEST,
        CLIENT_RESERVATION_MODIFICATION_SUCCESS,
        CLIENT_RESERVATION_MODIFICATION_REFUSED,
        CLIENT_PAYMENT_SUCCESS,
        CLIENT_RESERVATION_CONFIRMATION,
        CLIENT_RESERVATION_ANNULATION_REQUEST,
        CLIENT_RESERVATION_ANNULATION_SUCCESS,
        CLIENT_RESERVATION_ANNULATION_REFUSED,

        // User Notifications
        NEW_CLIENT_REGISTRATION,
        NEW_RESERVATION,
        RESERVATION_MODIFICATION_REQUEST,
        RESERVATION_MODIFICATION_SUCCESS,
        RESERVATION_MODIFICATION_REFUSED,
        RESERVATION_CONFIRMATION,
        RESERVATION_REFUSED,
        RESERVATION_CANCELLATION_REQUEST,
        RESERVATION_CANCELLATION_SUCCESS,
        RESERVATION_CANCELLATION_REFUSED,
        PAYMENT_RECEIVED
    }